Addition to OpenMDAO Sphinx extensions
mdolab/sphinx_mdolab_theme pull request #15
Opened 2023-04-06 00:24 UTC by kanekosh

## Purpose
This PR adds `run_sub.py` that was a part of the OpenMDAO 3.9's sphinx extensions but is currently missing in this repo.
`run_sub.py` is necessary to run the embedded code with MPI (I'm trying to add an MPI example in OpenAeroStruct docs).

I don't know how to test this. At this moment, no repo calls `run_sub.py` so this should not break anything.
I tested the new OAS docs build (with embedded MPI code) locally and it worked.

## Expected time until merged
A few days

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Testing

## Checklist

- [x] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

2023-04-06 13:42 UTC, eirikurj requested changes
For the RST flake8 issues, there are several options. 
We could include a local `.flake8` file to ignore RST as we are not building docs for this repo. However, this is problematic as `extend-ignore` overwrites our global one. This means we need to maintain a complete list of `extend-ignore`, and I would prefer not to.
Another option is to add `# noqa` where appropriate, to ignore some of these issues.

Overall, I would prefer to fix as many as possible. Also, even if not direction useful in this repo, I think RST303 is probably going to be an issue for us in other repos when using the custom directive. This we probably should add in our global `.flake8` file. 

I am open to other suggestions or comment.

2023-04-06 14:07 UTC, eirikurj commented
PR #16 should fix most of the issues `RST303` is however not fixed yet.

2023-04-06 14:17 UTC, eirikurj commented
PR https://github.com/mdolab/.github/pull/54, once merged, should take care of the remaining RST303 issues.

2023-04-06 15:43 UTC, kanekosh commented on sphinx_mdolab_theme/utils/docutil.py
> +    for code, tagls in input_blocks:
Fixed, thanks for pointing out

2023-04-10 10:00 UTC, eirikurj approved these changes

2023-04-10 10:00 UTC, merged